(function () {
    function addLegalFooter() {
        if (document.querySelector(".legal-footer")) {
            return;
        }

        var style = document.createElement("style");
        style.textContent = [
            ".legal-footer {",
            "    margin-top: 70px;",
            "    padding-top: 28px;",
            "    border-top: 1px solid #2a1838;",
            "    color: #9e79bd;",
            "    font-size: 0.85rem;",
            "    line-height: 1.7;",
            "}",
            ".legal-footer h2, .legal-footer h3 {",
            "    letter-spacing: 3px;",
            "    font-weight: normal;",
            "}",
            ".legal-footer h2 {",
            "    margin-top: 0;",
            "    font-size: 1rem;",
            "}",
            ".legal-footer h3 {",
            "    margin-top: 0;",
            "    color: #c56cff;",
            "    font-size: 0.9rem;",
            "}",
            ".legal-footer summary {",
            "    color: #c56cff;",
            "    cursor: pointer;",
            "    list-style: none;",
            "    padding: 10px 0;",
            "    text-shadow: 0 0 6px rgba(197,108,255,0.3);",
            "}",
            ".legal-footer summary::-webkit-details-marker {",
            "    display: none;",
            "}",
            ".legal-footer summary::before {",
            "    content: '[ + ] ';",
            "    color: #6d5b80;",
            "}",
            ".legal-footer details[open] summary::before {",
            "    content: '[ - ] ';",
            "}",
            ".legal-footer summary:hover {",
            "    color: #ffffff;",
            "}",
            ".legal-footer details {",
            "    border-bottom: 1px solid #2a1838;",
            "}",
            ".legal-footer details:last-child {",
            "    border-bottom: 0;",
            "}",
            ".legal-footer .legal-panel {",
            "    padding: 8px 0 22px 0;",
            "}",
            ".legal-footer dl {",
            "    display: grid;",
            "    grid-template-columns: minmax(120px, 180px) 1fr;",
            "    gap: 6px 18px;",
            "    margin: 12px 0 20px;",
            "}",
            ".legal-footer dt {",
            "    color: #6d5b80;",
            "}",
            ".legal-footer dd {",
            "    margin: 0;",
            "}",
            ".legal-footer .placeholder {",
            "    color: #d7b4ff;",
            "}",
            ".legal-footer .language-grid {",
            "    display: grid;",
            "    grid-template-columns: 1fr 1fr;",
            "    gap: 28px;",
            "}",
            "@media (max-width: 720px) {",
            "    .legal-footer .language-grid, .legal-footer dl {",
            "        grid-template-columns: 1fr;",
            "    }",
            "}"
        ].join("\n");
        document.head.appendChild(style);

        var footer = document.createElement("footer");
        footer.className = "legal-footer";
        footer.innerHTML = [
            "<h2>LEGAL ACCESS</h2>",
            "<details>",
            "    <summary>IMPRESSUM / LEGAL NOTICE</summary>",
            "    <div class=\"legal-panel language-grid\">",
            "        <section aria-labelledby=\"impressum-de\">",
            "            <h3 id=\"impressum-de\">IMPRESSUM</h3>",
            "            <p class=\"dim\">Angaben gem&auml;&szlig; &sect; 5 DDG</p>",
            "            <dl>",
            "                <dt>Betreiber</dt>",
            "                <dd>Atilla Can Basaran</dd>",
            "                <dt>Anschrift</dt>",
            "                <dd>Johannisstr. 136<br>49074 Osnabr&uuml;ck<br>Deutschland</dd>",
            "                <dt>Kontakt</dt>",
            "                <dd><a href=\"mailto:atillacanbasran@gmail.com\">atillacanbasran@gmail.com</a></dd>",
            "                <dt>Website</dt>",
            "                <dd>attianprotocol.net</dd>",
            "            </dl>",
            "        </section>",
            "        <section aria-labelledby=\"imprint-en\">",
            "            <h3 id=\"imprint-en\">LEGAL NOTICE</h3>",
            "            <p class=\"dim\">Information according to Section 5 DDG</p>",
            "            <dl>",
            "                <dt>Operator</dt>",
            "                <dd>Atilla Can Basaran</dd>",
            "                <dt>Address</dt>",
            "                <dd>Johannisstr. 136<br>49074 Osnabr&uuml;ck<br>Germany</dd>",
            "                <dt>Contact</dt>",
            "                <dd><a href=\"mailto:atillacanbasran@gmail.com\">atillacanbasran@gmail.com</a></dd>",
            "                <dt>Website</dt>",
            "                <dd>attianprotocol.net</dd>",
            "            </dl>",
            "        </section>",
            "    </div>",
            "</details>",
            "<details>",
            "    <summary>DATENSCHUTZERKL&Auml;RUNG / PRIVACY POLICY</summary>",
            "    <div class=\"legal-panel language-grid\">",
            "        <section aria-labelledby=\"datenschutz-de\">",
            "            <h3 id=\"datenschutz-de\">DATENSCHUTZERKL&Auml;RUNG</h3>",
            "            <p>Diese Website ist ein statisches pers&ouml;nliches Webangebot. Sie verwendet keine eigenen Cookies, keine Analyse-Tools, kein Tracking, keinen Newsletter und keine Kommentarfunktion.</p>",
            "            <p>Beim Aufruf der Website k&ouml;nnen durch Hosting- und Infrastruktur-Anbieter technische Zugriffsdaten verarbeitet werden, zum Beispiel IP-Adresse, Datum und Uhrzeit des Zugriffs, angeforderte Datei, Referrer und User-Agent. Die Verarbeitung dient der Auslieferung, Sicherheit und Stabilit&auml;t der Website. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO.</p>",
            "            <p>Wenn du per E-Mail Kontakt aufnimmst, werden die von dir &uuml;bermittelten Angaben zur Bearbeitung der Anfrage verarbeitet. Du hast nach Ma&szlig;gabe der DSGVO insbesondere Rechte auf Auskunft, Berichtigung, L&ouml;schung, Einschr&auml;nkung der Verarbeitung, Widerspruch und Beschwerde bei einer Datenschutzaufsichtsbeh&ouml;rde.</p>",
            "        </section>",
            "        <section aria-labelledby=\"privacy-en\">",
            "            <h3 id=\"privacy-en\">PRIVACY POLICY</h3>",
            "            <p>This website is a static personal website. It does not set its own cookies, use analytics tools, tracking, newsletters, or comment forms.</p>",
            "            <p>When the website is accessed, hosting and infrastructure providers may process technical access data such as IP address, date and time of access, requested file, referrer, and user agent. This processing serves delivery, security, and stability of the website. The legal basis is Art. 6(1)(f) GDPR.</p>",
            "            <p>If you contact the operator by email, the information you provide will be processed to respond to the request. Subject to the GDPR, you have rights including access, rectification, erasure, restriction of processing, objection, and the right to lodge a complaint with a data protection supervisory authority.</p>",
            "        </section>",
            "    </div>",
            "</details>"
        ].join("\n");

        document.body.appendChild(footer);
    }

    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", addLegalFooter);
    } else {
        addLegalFooter();
    }
}());
